create table Posts(
  id int primary key generated by default as identity,
  userId int,
  title varchar ,
  body varchar
);

insert into posts(userid, title, body) VALUES (1, 'dgdgd12', 'fnbfnfn bbvnqwqw');
insert into posts(userid, title, body) VALUES (1, 'vvbvb12', 'qwqwvnvnfn fnfn');
insert into posts(userid, title, body) VALUES (1, '1vbvb2', 'qwhfhf nvbnqw');
insert into posts(userid, title, body) VALUES (1, '1vbvb2', 'qxvxvxvxwqwxvx');
insert into posts(userid, title, body) VALUES (1, '12vbvb', 'qxvxvwqw');
insert into posts(userid, title, body) VALUES (1, '1cbcb2', 'qw546456qw');
insert into posts(userid, title, body) VALUES (1, '1gdfgdg2', 'qwq546456fxvxw');
insert into posts(userid, title, body) VALUES (1, '12dgdfg', 'qwq45345fvcxvw');
insert into posts(userid, title, body) VALUES (1, '12sfsfcvsv', 'qwxvxvrtetqw');
insert into posts(userid, title, body) VALUES (1, 'sfsfc vxv512', 'qwq534646xfvxv xcvw');

insert into posts(userid, title, body) VALUES (2, '12ada', 'qwdfgd34535qw');
insert into posts(userid, title, body) VALUES (2, '12adasd', 'qwdgdxvxcvqw');
insert into posts(userid, title, body) VALUES (2, '12zxc', 'qwqgGdfggdfgw');
insert into posts(userid, title, body) VALUES (2, '12zc', 'qwagggrqw');
insert into posts(userid, title, body) VALUES (2, '12zc', 'qagwqw');
insert into posts(userid, title, body) VALUES (2, '12zc', 'qwzxcvxcrsgqw');
insert into posts(userid, title, body) VALUES (2, '12zc', 'qwwerwrqw');
insert into posts(userid, title, body) VALUES (2, '12zc', 'qsfsfwqw');
insert into posts(userid, title, body) VALUES (2, '12', 'qsfsfwqw');
insert into posts(userid, title, body) VALUES (2, '12sgsg', 'qwqwsfsf');

insert into posts(userid, title, body) VALUES (3, '35312', 'qwq 4674 645747 w');
insert into posts(userid, title, body) VALUES (3, '545612', 'qw dgdgdsg536 cv47b qw');
insert into posts(userid, title, body) VALUES (3, '4564612', 'qwqege gege gegew');
insert into posts(userid, title, body) VALUES (3, 'etetdfgd 12', 'qwq zgzgrge gerw');
insert into posts(userid, title, body) VALUES (3, 'yey dgd546712', 'qwqdgdg456 yeryw');
insert into posts(userid, title, body) VALUES (3, 't r r dgd4564612', 'qwqdsgdgdgw');
insert into posts(userid, title, body) VALUES (3, 'thrrh575bvnv fhn12', 'qwqgnghjgjaew');



create table Posts(
      id int primary key generated by default as identity,
      title varchar ,
      body varchar
);

insert into posts(title, body) VALUES ( 'dgdgd12', 'fnbfnfn bbvnqwqw');
insert into posts(title, body) VALUES ( 'vvbvb12', 'qwqwvnvnfn fnfn');
insert into posts(title, body) VALUES ( '1vbvb2', 'qwhfhf nvbnqw');
insert into posts(title, body) VALUES ( '1vbvb2', 'qxvxvxvxwqwxvx');
insert into posts(title, body) VALUES ( '12vbvb', 'qxvxvwqw');
insert into posts(title, body) VALUES ( '1cbcb2', 'qw546456qw');
insert into posts(title, body) VALUES ( '1gdfgdg2', 'qwq546456fxvxw');
insert into posts(title, body) VALUES ( '12dgdfg', 'qwq45345fvcxvw');
insert into posts(title, body) VALUES ( '12sfsfcvsv', 'qwxvxvrtetqw');
insert into posts(title, body) VALUES ( 'sfsfc vxv512', 'qwq534646xfvxv xcvw');

insert into posts(title, body) VALUES ( '12ada', 'qwdfgd34535qw');
insert into posts(title, body) VALUES ('12adasd', 'qwdgdxvxcvqw');
insert into posts(title, body) VALUES ('12zxc', 'qwqgGdfggdfgw');
insert into posts(title, body) VALUES ('12zc', 'qwagggrqw');
insert into posts(title, body) VALUES ('12zc', 'qagwqw');
insert into posts(title, body) VALUES ( '12zc', 'qwzxcvxcrsgqw');
insert into posts(title, body) VALUES ( '12zc', 'qwwerwrqw');
insert into posts(title, body) VALUES ( '12zc', 'qsfsfwqw');
insert into posts(title, body) VALUES ( '12', 'qsfsfwqw');
insert into posts(title, body) VALUES ( '12sgsg', 'qwqwsfsf');

insert into posts(title, body) VALUES ( '35312', 'qwq 4674 645747 w');
insert into posts(title, body) VALUES ( '545612', 'qw dgdgdsg536 cv47b qw');
insert into posts(title, body) VALUES ( '4564612', 'qwqege gege gegew');
insert into posts(title, body) VALUES ( 'etetdfgd 12', 'qwq zgzgrge gerw');
insert into posts(title, body) VALUES ( 'yey dgd546712', 'qwqdgdg456 yeryw');
insert into posts(title, body) VALUES ( 't r r dgd4564612', 'qwqdsgdgdgw');
insert into posts(title, body) VALUES ( 'thrrh575bvnv fhn12', 'qwqgnghjgjaew');
